apiVersion: v1
kind: ConfigMap
metadata:
  name: parcelpulse-config
  namespace: parcelpulse
data:
  APP_NAME: parcelpulse-api
  APP_ENV: kubernetes
  API_PORT: "8000"
  MODEL_PATH: /models/model.joblib
